### PR TITLE
[wip] test if building yt 3.3 on conda-forge will work

### PR DESCRIPTION
**Pull request by ngoldbaum**
DO NOT MERGE!

I just want to build on conda-forge before I tag 3.3.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
@pelson @jakirkham @msarahan I'd like to enable appveyor testing and windows builds for this feedstock, but as far as I can see you need to be a conda-forge maintainer to do that since I'd need API tokens for the CI services. If so, can one of you help me out with that?

**Comment by msarahan** [comment]
I think conda smithy can help you with that. Just remove any selectors that exclude windows, and run

    conda smithy rerender

**Comment by jakirkham** [comment]
Oh good. Looks like you got everything worked out.

**Comment by jakirkham** [comment]
I suspect that the Windows Python 3.4 32-bit pinning of `conda-build` is causing the two AppVeyor failures seen here. Am proposing that we drop this pinning in PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/21 ) so that we don't have to workaround it in other ways.

**Comment by ngoldbaum** [comment]
I think it was because I was uploading the tarball in a weird way. Let's see if it fails over in https://github.com/conda-forge/yt-feedstock/pull/4

**Pull request closed without merging**
