### PR TITLE
Enable builds on osx_arm64

### PR DESCRIPTION
**Pull request by Xarthisius**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by munkm — COMMENTED** [review]
It looks like you've bumped some of the linux builds too. Is that intentional?

**Comment by Xarthisius** [comment]
> It looks like you've bumped some of the linux builds too. Is that intentional?

That happened after I rerendered the recipes. I won't pretend to know what conda smithy is doing.

**Comment by munkm** [comment]
> > It looks like you've bumped some of the linux builds too. Is that intentional?
> 
> That happened after I rerendered the recipe. I won't pretend to know what conda smithy is doing.

🧙 🪄 ⭐

**Comment by Xarthisius** [comment]
So the good news is that osx/arm64 builds just fine. Bad news is that latest template for linux/aarch and linux/pcc64 seems broken... fun...

**Pull request merged**
