### PR TITLE
pyembree support

### PR DESCRIPTION
**Pull request by scopatz**
Hopefully it just works.

### CODE REVIEW

**Comment by scopatz** [comment]
RTFD @scopatz :) http://yt-project.org/doc/visualizing/unstructured_mesh_rendering.html#installation

**Comment by scopatz** [comment]
OK, Travis is failing because of timeouts. I tried restarting it, but it didn't work for some strange reason. Can you try @ngoldbaum, since I don't have rights on this repo...

**Comment by jakirkham** [comment]
Would recommend setting `osx_image` just like in PR ( https://github.com/conda-forge/staged-recipes/pull/1716 ).

**Comment by ngoldbaum** [comment]
It looks like this is OK, except one of the appveyor builds died due to what looks like transient network issues: https://ci.appveyor.com/project/conda-forge/yt-feedstock/build/1.0.10/job/2fuwqhdk42r70o5p

**Comment by scopatz** [comment]
You should be able to restart that one job, then.  I don't have permissions, I don't think

**Comment by ocefpaf** [comment]
> You should be able to restart that one job, then.

Sadly AppVeyor does not have the same granular control as `Travis-CI`. The whole build must be re-started.

>  I don't have permissions, I don't think

I already did that for you, but feel free to merge without it since it seems pretty much OK IMO.

**Comment by jakirkham** [comment]
Please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.3.2` and do a build number bump to fix the OS X image back to 10.9.

**Pull request merged**
