### PR TITLE
remove embree dependency

### PR DESCRIPTION
**Pull request by ngoldbaum**
I've had user reports about issues with importing pyembree. We don't actually need to depend on pyembree and given the fact that an upstream pyembree update has silently caused an issue here with yt I'm just going to remove it as a dependency. Here's the screenshot the user shared with me:

image

I think technically I could leave it as a dependency and just increment the build number to resolve the issue but I don't want to deal with this again.

Ping @scopatz since I think it was his pyembree update that triggered this.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
Do you mind pushing an empty/negligible commit? I'd like to keep the log around for a `conda` issue report.

**Comment by ngoldbaum** [comment]
sure :)

**Comment by jakirkham** [comment]
Thanks.

For reference, noted this particular failure as part of issue ( https://github.com/conda/conda/issues/7193 ) in [this comment]( https://github.com/conda/conda/issues/7193#issuecomment-384718760 ).

**Pull request merged**
