### PR TITLE
unpin unyt

### PR DESCRIPTION
**Pull request by chrishavlin**
The latest version of yt is compatible with unyt>=3 but it's still pined to <3 here. And since unyt never had a 2.9.x release that pinned numpy < 2.0 (despite not being compatible with numpy >= 2), you actually can end up with a broken environment (in a fresh py3.10 environment, `conda install yt` results in yt 4.3.1, unyt 2.9.5 and numpy 2.1.1). Pretty sure we just need to change this one line, but I'm not super familiar with maintaining conda feedstocks, so let me know if anything else needs to be done.

### CODE REVIEW

**Comment by Xarthisius** [comment]
Looks like it installs:
```
unyt:               3.0.3-pyhd8ed1ab_0         conda-forge
```
then dies during import with:

```
import: 'yt'
+ pip check
yt 4.3.1 has requirement unyt>=2.9.2, but you have unyt 0.0.0.
WARNING: Tests failed for yt-4.3.1-py311h14de704_1.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3523, in test
    utils.check_call_env(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/yt_1726167167821/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:
```

**Comment by chrishavlin** [comment]
hmm, well not really sure what's going on. was able to reproduce the build failure locally, but the import tests do actually run ok, it's the pip check that is failing -- e.g., i modified the tests in `recipe/meta.yaml` to :

```
test:
  imports:
    - yt
    - unyt
  commands:
    - python -c "import yt; import unyt; print(yt.__version__); print(unyt.__version__)"
    - python -c 'from yt.testing import fake_amr_ds; import yt; ds = fake_amr_ds(); slc = yt.SlicePlot(ds,"x",("stream","Density")); slc.save()'
    - yt --help
    - conda list -vvv
    - conda list --explicit
    - pip check
  requires:
    - pip
```

And everything runs as expected until the pip check

**Comment by yut23** [comment]
The pip check failures should be fixed by https://github.com/conda-forge/unyt-feedstock/pull/39. We should also add `setuptools >=61.2` to the host section like the linter says, so we're consistent with the pyproject.toml.

**Review by yut23 — CHANGES_REQUESTED** [review]
The build number (line 16) needs to be bumped since we aren't changing the yt version.

**Comment by chrishavlin** [comment]
awesome, thanks for the help there, @yut23 !! will bump the build number and setuptools here.

**Comment by ax3l** [comment]
@conda-forge admin, please rerender

**Comment by ax3l** [comment]
Huh:
```
+ pip check
yt 4.3.1 has requirement unyt>=2.9.2, but you have unyt 0.0.0.
```

**Comment by chrishavlin** [comment]
@ax3l , @yut23 fixed that over in the unyt feedstock in https://github.com/conda-forge/unyt-feedstock/pull/39 so I think the builds here will fail until that is merged.

**Comment by chrishavlin** [comment]
it might make sense to exclude some unyt versions in the yt recipe... maybe `unyt>=2.9.2,!=3.0.0,!=3.0.1,!=3.0.2` since 3.0.3 should be OK after https://github.com/conda-forge/unyt-feedstock/pull/39 goes in.

**Comment by yut23** [comment]
I think that would only be necessary if yt needs to check the unyt version at runtime. I don't see anything like that from a quick grep, but I'm not super familiar with the codebase.

**Comment by yut23** [comment]
@conda-forge/yt can someone re-run the checks? The fixed build of unyt is now up on conda-forge.

**Comment by ax3l** [comment]
@chrishavlin you could briefly close and reopen the PR to trigger CI, in case you have no restart permissions on the `Checks` tab

**Comment by Xarthisius** [comment]
retriggered manually

**Comment by ax3l** [comment]
Yay, this is looking good now

**Pull request merged**
